### ISSUE TITLE
2008年 魔法禁書目錄 

### ISSUE THREAD

**Issue by katy50306** [katy50306/message#27]
Submitter: BSK
檔案似乎缺失了，謝謝您的貢獻，希望能快點修復，最近想好好複習一下經典><
抱歉剛剛順手留下Email了sor

**Comment by katy50306** [comment]
請再詳細說明檔案缺失的情形
瞄了一下1-24應該都在

**Comment by BSK-1994** [comment]
好的，點開連結後顯示為404找不到網頁[https://kat-ani.win/2008/index.htm](url)
我也想過是不是自己電腦設定的問題，但點選其他動畫又都一切正常

**Comment by BSK-1994** [comment]
剛剛嘗試了一下發現，位於2010年的魔法禁書目錄II 也有相同狀況

**Comment by katy50306** [comment]
感謝抓蟲  
先給連結
[1季](https://drive.google.com/drive/folders/16tkDiqhRDywAcpWhhq6bmFaDonDF6Ch_?usp=sharing)
[2季](https://drive.google.com/drive/folders/1qWqGramdAnADD7xWY1eTQixq8Ay1Hqla?usp=sharing)

**Comment by BSK-1994** [comment]
不會，我這邊才感謝，有空我幫忙把所有連結點一點，有問題再集中回報，辛苦您啦:")
