### ISSUE TITLE
閒聊題外話

### ISSUE THREAD

**Issue by katy50306** [katy50306/message#4]
Submitter: 莓反應只是個伸手廚
白熊大你好！
關於您當年在伊莉發表的文章，有沒有考慮更新載點嗎？
如果沒有的話，那就裝死吧！
不然被一些正義小超人檢舉對您來說也相當麻煩…

**Comment by katy50306** [comment]
其實很久沒去伊莉PO了XD
更新會有以下問題
1. 當初發文後90天鎖文，要改文章要先向版主申請精華再改    
2. 不可以只放連結，以前只丟首頁的方式不可行  
3. 其實就是我懶Orz  

反正運氣好有搜到就用  
沒搜到也不缺我一個

**Comment by KevinYu0504** [comment]
我當初是從 CR 那邊知道熊大的，這裡的小天地也是偶然得知，
且幫到我不少，以前硬碟炸過一次，很多東西消失了，都是靠白熊大補回來的 >w<

**Comment by katy50306** [comment]
炸過一次記得要做好備份阿~~~   
不然下次會再發生一次的...
