### ISSUE TITLE
下載空間由google dirve改onedrive之意見

### ISSUE THREAD

**Issue by katy50306** [katy50306/message#59]
by小白熊

因應Google drive漲價及無限空間限縮(或取消)，目前計畫改放於onedrive個人版上
價格相對便宜

改版後google 每月每帳630 / 5TB須5帳=>37800/年
onedrive家庭版6帳6TB=>3190/年 

不過有觀察到下載速度稍微慢了點(單檔3MB/s 下載速度超過30的應會碰到限制)
[測試檔](https://1drv.ms/u/s!Ap9vPMBQMJhVykoeLwHOXyzYHg8m?e=rlOupK)

參考
[[情報]Google Workspace 限制](https://www.ptt.cc/bbs/Free_box/M.1650516015.A.EED.html)
[Re: [情報] Google Workspace 限制 (官方文檔)](https://www.ptt.cc/bbs/Free_box/M.1652612831.A.72D.html)

以下開放討論XD

**Comment by kat-ani** [comment]
## 暱稱

路人甲

## 內容

好久沒回來這裡了，很驚喜仍活耀著，感謝白熊大如此辛苦的付出 :D

**Comment by kat-ani** [comment]
## 暱稱

路人

## 內容

還是感謝白熊大這麼多年來的堅持與辛苦分享，OD 雖然確實比不上 GD，但考慮到價格問題，便宜些也好，至少希望白熊大這邊分享能夠活得越久越好 ~
