### ISSUE TITLE
關於プリンセスコネクト！Re:Dive Season2 

### ISSUE THREAD

**Issue by kat-ani** [katy50306/message#61]
## 暱稱

狙擊喵

## 內容

版主您好
感謝您無私分享各類作品
我想請問一下,RE:DIVE S2的集數未來會補完嗎?
目前我只在上面看到第一集?感謝!

**Comment by katy50306** [comment]
雪飄的後期大概離開圈子了
我都沒收到繁化稿...

先拿B站的墊檔吧
https://drive.google.com/drive/folders/18wuWDNqd55gw9c0BJfQGbpkCF01dfORu?usp=sharing

**Comment by kat-ani** [comment]
## 暱稱

狙擊喵

## 內容

感謝版主,謝謝
