### ISSUE TITLE
支持

### ISSUE THREAD

**Issue by kat-ani** [katy50306/message#64]
## 暱稱

SnoopyK

## 內容

純支持哦! 到這網站來看也十年了~  非常感謝站主，我記得以前還會有開箱分享 XD
再次感謝

**Comment by kat-ani** [comment]
## 暱稱

小白熊

## 內容

其實東西愈買愈多啦，懶的開了

最近是有考慮要不要收攤惹
代理商最近幾年很猛
想看的幾乎都有代理
字幕組也愈來愈少做了

**Comment by katy50306** [comment]
其實東西愈買愈多啦，懶的開了

最近是有考慮要不要收攤惹
代理商最近幾年很猛
想看的幾乎都有代理
字幕組也愈來愈少做了
