### ISSUE TITLE
天才麻將少女24話

### ISSUE THREAD

**Issue by kat-ani** [katy50306/message#66]
## 暱稱

sin

## 內容

剛剛抓完全部
天才麻將少女24話一直被win判出惡意軟體
Trojan:Script/Wacatac.H!ml
katani\[#CHAT RUMBLE#][Saki][24][BIG5][x264_aac][1280x720][6BD58FEB].rar

**Comment by katy50306** [comment]
hi 原檔用virustotal看應該是沒問題的
https://www.virustotal.com/gui/file/8572a3a653e0c7178737e9d58f4f648f2da28875854ae04a6240fa9e368f4711/detection

不過我重傳了一個
https://1drv.ms/u/s!AtUNW28lycN2mDsCk7u3tUHjvh-o?e=a49QNx

您可以再看看有沒有報毒

**Comment by kat-ani** [comment]
## 暱稱

sin

## 內容

已下載此重傳檔案，檔案正常

原本的不知道為啥一下下來就被M$內建防毒判那個
