### ISSUE TITLE
Missing: あにトレ！EX / 動畫鍛鍊！EX - EP08

### ISSUE THREAD

**Issue by kat-ani** [katy50306/message#67]
## 內容

如題
<https://onedrive.live.com/?authkey=%21AOw9uUu4QiLtn8g&id=4CB8F55CB0677A2F%21742&cid=4CB8F55CB0677A2F>

**Comment by katy50306** [comment]
手上檔案已遺失無法補檔
---
The file is missing in my HDD so I can't re-upload it

**Comment by kat-ani** [comment]
## 暱稱



## 內容

No worries bro.
Thank you for your quick response.
